add 2moons distribution and affine transformation
Justinezgh/SBI-Diff-Simulator pull request #14
Opened 2022-05-09 16:17 UTC by Justinezgh

![image](https://user-images.githubusercontent.com/72011736/167453215-e7343bdc-67e7-4054-8718-b905540d4aa4.png)
![image](https://user-images.githubusercontent.com/72011736/167453231-06402d0c-af53-4e00-be22-b254d1f5e79b.png)

[notebook](https://github.com/Justinezgh/SBI-Diff-Simulator/blob/61b3f51a42153072ac81bc2c8befe99f19159766/notebooks/smoothNF_VS_affineNF.ipynb)

2022-05-09 20:05 UTC, EiffL commented on sbids/tasks/two_moons.py
> +from sklearn.datasets import make_swiss_roll
```suggestion
```

2022-05-09 20:11 UTC, EiffL commented
Ok, that's great @Justinezgh ! Now, what we want is for this notebook to produce a beautiful plot that we can put in the paper and future presentations.

2022-05-09 20:13 UTC, EiffL commented
Kind of like the plots we had there: https://eiffl.github.io/Paris2022/#/30/0/0

2022-05-09 20:14 UTC, EiffL commented on notebooks/smoothNF_VS_affineNF.ipynb
> +        "!pip install --quiet git+https://github.com/astrodeepnet/sbi_experiments.git"
Why do we need sbi_experiments?

2022-05-09 20:16 UTC, Justinezgh commented on notebooks/smoothNF_VS_affineNF.ipynb
> +        "!pip install --quiet git+https://github.com/astrodeepnet/sbi_experiments.git"
we don't, forgot to change it

2022-05-10 11:00 UTC, EiffL requested changes
My main comment is to use this notebook to make publishable plots. You can even create a folder "figures" in which you store the figures that this notebook generates, and these plots are intended to go directly into a paper.

Can you update the notebook accordingly? 

Once this is done, this is done and we can focus on something else

2022-05-10 11:52 UTC, Justinezgh commented
![image](https://user-images.githubusercontent.com/72011736/167622066-2d01b932-3bcb-41f3-8721-9195dad5642c.png)
![image](https://user-images.githubusercontent.com/72011736/167622080-8ea43716-21f5-42fe-b501-4df06b7aebc0.png)

2022-05-10 12:35 UTC, EiffL commented
Tres jolie :-) But what I was saying last night, is that instead of sampling from the points you get the gradients for from the true distribution, maybe we want to sample the points from the **learned** distribution. Have you tried that? Is it not looking good?
We also need a plot of the true score for the true distribution :-)

2022-05-10 17:49 UTC, EiffL commented
yep :-) that looks good I think

2022-05-10 20:15 UTC, Justinezgh commented
ok cool :) 


I ran the 2moons experiments on azure today, for each nb of simulations 10 NFs (with different initialization seed) are trained 
![image](https://user-images.githubusercontent.com/72011736/167713852-1ae57b37-751d-443f-9e8f-b71ac13e9c36.png)
![image](https://user-images.githubusercontent.com/72011736/167713870-74752966-c216-482b-bb40-4fa78444d289.png)

2022-05-11 06:23 UTC, aboucaud commented
Looks really good. Especially the bump that we saw previously at ~200 sims seems to have disappeared.

2022-05-11 10:50 UTC, EiffL commented
:-D makes me very happy. One comment and a question:
- Maybe on the x axis here we could say, "number of training samples", here we are not really doing SBI, it's just density estimation, so the word simulation could be misleading. On the first plot, on the y axis it says `nlp` when I think you want to say `NLL` in this particular case.

- Just a question (not saying we should do it necessarily), have you tried training just with the score and see what these plots would look like?

2022-05-11 10:52 UTC, EiffL approved these changes
LGTM, I'd just recommend also including the scripts/notebook used to generate these nice plots as a fucntion of number of simulations

2022-05-11 11:30 UTC, Justinezgh commented
No I haven't try with just the score but I can

2022-05-11 13:43 UTC, EiffL commented
Ok, not good I guess. Probably this normalization question we talked about. It would mess with both metrics

2022-05-11 19:35 UTC, Justinezgh commented
@EiffL can I merge ?

2022-05-11 21:59 UTC, EiffL commented
All good for me

2022-05-11 22:07 UTC, merged